server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: "jdbc:mysql://localhost:3306/library?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      encoding: utf-8
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

file:
  upload-dir: ${user.home}/.library/uploads/covers
